### ISSUE TITLE
Proposal to change the data format again

### ISSUE THREAD

**Issue by Anirudh-S-Kumar** [aflah02/SemWiseResourcesIIIT#41]
End of last year/Start of this year we changed to YAML instead of just appending content in the markdown
I think the YAML format is very unwieldy and has caused a lot of problems.

I suggest we move forward to using JSON instead as it 
- Human readable like YAML
- Has easier parsing

What do you think @Anindya-Prithvi @aflah02 ?

**Comment by aflah02** [comment]
What kind of issues do you find YAMLs to cause? I think the !!python like stuff could be removed by spending some time on it if that is your concern. I suppose JSON would be less readable than YAML

**Comment by Anirudh-S-Kumar** [comment]
I think it's more error prone to cause formatting errors in YAML than it is for JSON, and yea the !!python stuff stuff looks very annoying

**Comment by Anindya-Prithvi** [comment]
I support this move...yaml does have word
weird formatting just to make it parseable

**Comment by Anindya-Prithvi** [comment]
and while we are at it... it is worth to note that we can add columns very easily... and the best column to add is "rating" 👺

**Comment by Anirudh-S-Kumar** [comment]
Why do we need rating for resources 💀. The repo is just meant as place for study material as of now. 

There are other things that would be better to implement like department, specialisation courses (like ones required by CSAI)

**Comment by Anirudh-S-Kumar** [comment]
We could do something like this maybe? It's a bit more verbose, but I think more readable and less error prone 

```yaml
Semester 1:
  IP:
    Resources:
    - '[Code with Harry Python Playlist Hindi](https://www.youtube.com/playlist?list=PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME)'
    - '[Programming with Mosh Python 6 Hrs Vid](https://www.youtube.com/watch?v=_uQrJ0TkZlc)'
    - '[Corey Schafer OOPs Concepts](https://www.youtube.com/playlist?list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc)'
Semester 2:
  DSA:
    Resources:
    - '[DSA Abdul Bari Sir](https://www.youtube.com/playlist?list=PLAXnLdrLnQpRcveZTtD644gM9uzYqJCwr)'
    - '[Code with Harry Python Playlist Hindi](https://www.youtube.com/playlist?list=PLu0W_9lII9agICnT8t4iYVSZ3eykIAOME)'
    - '[Programming with Mosh Python 6 Hrs Vid](https://www.youtube.com/watch?v=_uQrJ0TkZlc)'
    - '[Corey Schafer OOPs Concepts](https://www.youtube.com/playlist?list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc)'
    Notes:
    - Easy aah course 
```
